export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR';

export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';

export const UPDATE_RECIPE_ERROR = 'UPDATE_RECIPE_ERROR';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
